### Vince Fredrick C. Dela Cruz  2 ECE - A

## EXPERIMENT 3

In [1]:
import pandas as pd

### A. POSITIONAL AND LABEL-BASED SLICING

In [2]:
cars = pd.read_csv('cars.csv')
car_names = cars[['Model']]
#Using positional slicing, create cars 6 to 10 containing rows 6 through 10 of the dataset, where the first data row is row 1
cars_6_to_10 = cars.iloc[[6,7,8,9,10]] # splices the list and grabs these rows.
cars_6_to_10 = cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']] # picks the specific data we want to grab from the list

cars_6_to_10.index = range(1, len(cars_6_to_10) + 1) # so the data row starts at 1

#### Output:

In [3]:
car_names

                  Model
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [4]:
car_names.shape # displays the shape of the list above

(32, 1)

In [5]:
cars.shape # displays the shape of the whole list of cars.csv

(32, 12)

In [6]:
cars_6_to_10

        Model   mpg  cyl   hp  gear
1  Duster 360  14.3    8  245     3
2   Merc 240D  24.4    4   62     4
3    Merc 230  22.8    4   95     4
4    Merc 280  19.2    6  123     4
5   Merc 280C  17.8    6  123     4

### B. MODEL LOOKUP

In [7]:
# Use Boolean indexing on the Model column to answer both requests.
toyota = cars.loc[(cars['Model']=='Toyota Corolla')] # takes the whole row of the model
pontiac = cars.loc[(cars['Model'] == 'Pontiac Firebird'), ['Model', 'mpg', 'hp', 'wt']] # takes these specific columns from a row

#### Output:

In [8]:
toyota

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [9]:
pontiac

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

### C. MULTI-MODEL SUBSETTING

In [10]:
m1 = cars.loc[(cars['Model']=='Datsun 710') | (cars['Model']=='Lotus Europa') | (cars['Model']=='Ferrari Dino')] # gets multiple rows
selected_cars = pd.DataFrame(m1, columns = ['Model','mpg','cyl', 'hp', 'gear']) # creates the new data frame

#### Output:

In [11]:
selected_cars

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

In [12]:
selected_cars.shape

(3, 5)